# This component is already included in the 'Polyglot Demo' system here: https://github.com/benwilcock/backstage-catalogs/blob/main/system-polyglot-demo.yml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-djl-demo
  description: Spring Boot Deep Java Learning (ML) Demo
  links:
    - url: https://github.com/benwilcock/springboot-djl-demo
      title: Source Code on GitHub
      icon: github
      type: source
  tags:
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=springboot-djl-demo'
spec:
  type: service
  lifecycle: experimental
  system: polyglot-demo-apps
  owner: user:ben.wilcock
  providesApis:
    - sentiments-api
  profile:
    displayName: Sentiment Analysis Demo Application

# APIs
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sentiments-api
  description: Used to perform sentiment analysis using a REST style API.
  links:
    - url: https://github.com/benwilcock/springboot-djl-demo
      title: Source Code on GitHub
      icon: github
      type: source
  annotations:
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/part-of=sspringboot-djl-demo"
    # backstage.io/techdocs-ref: url:https://github.com/benwilcock/springboot-djl-demo/blob/main/
spec:
  type: openapi
  lifecycle: production
  owner: group:mambg-tmm-team
  system: polyglot-demo-apps
  definition:
    $text: https://github.com/benwilcock/mambg-tmm-team/blob/main/openapi/openapi.json
---