# This component is already included in the 'Polyglot Demo' system here: https://github.com/benwilcock/backstage-catalogs/blob/main/system-polyglot-demo.yml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-djl-demo
  description: Spring Boot Deep Java Learning (ML) Demo
  tags:
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=springboot-djl-demo'
spec:
  type: service
  lifecycle: experimental
  owner: mambg-tmm-team