# GET http://localhost:8080/api/analyze
# content-Type: application/json

GET http://localhost:8080/v3/api-docs 
content-Type: application/json

###
POST http://localhost:8080/api/analyze 
content-Type: application/json

{
  "sentence": "I like DJL. DJL is the best DL framework!"
}

###
POST http://localhost:8080/api/analyze 
content-Type: application/json

{
  "sentence": "I like Red Hat Developer Hub. It's is the best internal developer portal I've ever used!"
}

###
POST http://localhost:8080/api/analyze 
content-Type: application/json

{
  "sentence": "I hate Dil. Of all the herbs in all the world, this is the one I avoid the most!"
}

###
POST http://localhost:8080/api/analyze 
content-Type: application/json

{
  "sentence": "I do like Bananas. But I don't like them too ripe, and I don't like them under-ripe either. They're OK if they're just right."
}

### Negative cases
POST http://localhost:8080/api/analyze 
content-Type: application/json

{
  "sentence": ""
}