apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: springboot-djl-demo
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
  name: springboot-djl-demo
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/language: java
        apps.tanzu.vmware.com/pipeline: test
    - name: testing_pipeline_params
      value:
        source-sub-path: .
    - name: api_descriptor
      value:
        type: openapi
        location:
          path: "/v3/api-docs"
        system: polyglot-demo-apps
        owner: mambg-tmm-team
        description: "An API endpoint that can analyze the positive or negative sentiment in a statement."
  source:
    git:
      ref:
        branch: main
      url: https://github.com/benwilcock/springboot-djl-demo
